name = "my-vless" # todo
main = "./src/main.ts"
compatibility_date = "2022-05-03"
workers_dev = true # should be deployed to *.workers.dev

[vars]
TEST_VAR = "example_dev_token"

[env.dev]
name = "my-vless-dev"
routes = [{ pattern = "cf-vless.zizi.press", custom_domain = true }]

[env.dev.vars]
TEST_VAR = "TEST_VAR_DEV"
