name: Deploy

on:
  push:
    branches:
      - main
      - test-cf
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|staging|prod>'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CF
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ github.event.inputs.environment || 'prod' }}
          workingDirectory: 'apps/cf-worker-vless'
          environment: ${{ github.events.inputs.environment || 'prod' }}
          secrets: |
            UUID
        env:
          UUID: ${{ secrets.UUID }}
